import { GoogleGenAI } from "@google/genai";
import { GeneratedPage } from '../types';
import { normalizeQuery, generateId } from '../lib/utils';

// Enhanced system instructions for Intebwio
const SYSTEM_INSTRUCTION = `
You are Intebwio, an intelligent web browser engine. Your job is to construct high-quality, interactive web pages dynamically based on user search queries.
You do not just summarize text; you build a visual experience.

Output strict JSON. The schema is:

{
  "title": "Page Title",
  "description": "SEO Description",
  "sections": [
    {
      "type": "hero | text_block | data_table | chart | gallery | key_stats | links | timeline | faq",
      "title": "Section Title (Optional)",
      ...specific_fields
    }
  ],
  "relatedTopics": ["Topic 1", "Topic 2"]
}

Types & Fields:
1. "hero": "headline", "subheadline", "backgroundImageQuery" (visual keyword).
2. "text_block": "content" (Rich markdown).
3. "data_table": "headers" (string[]), "rows" (string[][]), "source".
4. "chart": "chartType" ('bar'|'line'|'pie'), "data" ([{name, value}]), "xAxisLabel", "yAxisLabel".
5. "gallery": "images" ([{alt, caption, query}]).
6. "key_stats": "stats" ([{label, value, trend: 'up'|'down'|'neutral'}]).
7. "links": "links" ([{title, url, description}]).
8. "timeline": "events" ([{date, title, description}]). Use for histories, roadmaps, schedules.
9. "faq": "items" ([{question, answer}]). Use for guides, explanations.

Guidelines:
- Generate at least 6 diverse sections.
- Use "timeline" for queries involving history, evolution, or future plans.
- Use "faq" for "how to", "what is", or complex topics.
- Use "chart" and "key_stats" for comparisons, finance, or data-heavy topics.
- Ensure "links" are relevant. Use googleSearch to find real URLs if possible.
- Be authoritative yet accessible.
`;

export const generatePageContent = async (query: string, useFlash: boolean = false): Promise<GeneratedPage> => {
  // Always get the latest API key from the environment
  const apiKey = process.env.API_KEY;
  if (!apiKey) {
    throw new Error("API Key missing");
  }

  // Create a new instance right before the call as per instructions
  const ai = new GoogleGenAI({ apiKey });
  const modelId = useFlash ? 'gemini-3-flash-preview' : 'gemini-3-pro-preview';

  try {
    const response = await ai.models.generateContent({
      model: modelId,
      contents: `Construct an Intebwio web page for: "${query}". Make it comprehensive, visually rich, and structured.`,
      config: {
        systemInstruction: SYSTEM_INSTRUCTION,
        tools: [{ googleSearch: {} }],
        temperature: 0.5,
        // Optional: Disable or limit thinking to save tokens/quota if needed
        thinkingConfig: { thinkingBudget: 0 }
      },
    });

    let jsonString = response.text || "";
    // Robust cleanup to handle markdown fences and extra text
    const jsonMatch = jsonString.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      jsonString = jsonMatch[0];
    }

    let data;
    try {
      data = JSON.parse(jsonString);
    } catch (e) {
      console.error("JSON Parse Error", e, jsonString);
      throw new Error("The engine produced a malformed response structure. Please try again.");
    }

    const page: GeneratedPage = {
      id: normalizeQuery(query),
      query: query,
      title: data.title || query,
      description: data.description || "Generated by Intebwio",
      createdAt: Date.now(),
      lastUpdated: Date.now(),
      relatedTopics: data.relatedTopics || [],
      sections: (data.sections || []).map((section: any) => ({
        ...section,
        id: generateId()
      }))
    };

    return page;

  } catch (error: any) {
    console.error("Intebwio Generation Error:", error);
    
    // Robust Error Inspection for Quota Limits
    // The error might be deeply nested in error.error or just properties on the object
    const isQuota = 
        error.status === 429 || 
        error.code === 429 ||
        error.error?.code === 429 ||
        error.error?.status === 'RESOURCE_EXHAUSTED' ||
        error.message?.includes('429') || 
        error.message?.includes('quota') || 
        error.message?.includes('RESOURCE_EXHAUSTED') ||
        (error.toString && error.toString().includes('429'));

    if (isQuota) {
      const quotaError: any = new Error("QUOTA_EXHAUSTED");
      quotaError.originalMessage = error.message || "You exceeded your current quota.";
      throw quotaError;
    }
    
    throw new Error("Intebwio failed to build this page. Connectivity or model error.");
  }
};